# Load the environment generated by Home Manager for standalone installations.
hm_session_vars="$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"

if [[ -r "$hm_session_vars" ]]; then
  source "$hm_session_vars"
fi

unset hm_session_vars

if (( $+commands[mise] )); then
  eval "$(mise activate zsh)"
else
  export PATH="$HOME/.local/share/mise/shims:$PATH"
  rehash
fi

if (( $+commands[zoxide] )); then
  eval "$(zoxide init zsh)"
fi

if (( $+commands[starship] )); then
  eval "$(starship init zsh)"
fi

if (( $+commands[direnv] )); then
  eval "$(direnv hook zsh)"
fi
